[build]
publish = "FitSDK.doccarchive/"
###### Change it to your doccarchive file's name

[[redirects]]
from = "/documentation/*"
status = 200
to = "/index.html"

[[redirects]]
from = "/tutorials/*"
status = 200
to = "/index.html"

[[redirects]]
from = "/data/documentation.json"
status = 200
to = "/data/documentation/fitsdk.json"
###### Change it to name in ProjectName.doccarchive/data/documentation/...
# often just all lowercase of your project name
